name: Pull Kickstarter Stuff

permissions:
  contents: write

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetch-kickstarter-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch kickstarter stuff
        run: |
          curl -s https://www.kickstarter.com/projects/superitemstudios/donos-tale-relaunch/stats.json -o stats.json

          pledged_float=$(jq -r '.project.pledged' stats.json)
          pledged=$(printf "%.0f" "$pledged_float")
          backers=$(jq -r '.project.backers_count' stats.json)
          comments=$(jq -r '.project.comments_count' stats.json)
          state=$(jq -r '.project.state' stats.json)
          goal=15000

          percent=$(awk "BEGIN { printf \"%.2f\", ($pledged / $goal) * 100 }")

          echo "{
            \"pledged\": $pledged,
            \"percent\": $percent,
            \"goal\": $goal,
            \"backers\": $backers,
            \"comments\": $comments,
            \"state\": \"$state\",
            \"end_time\": \"2025-08-24T13:02:20-04:00\",
            \"updated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
          }" > kickstarter.json


      - name: Commit and push kickstarter.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kickstarter.json
          git commit -m "Update Kickstarter stats" || echo "No changes to commit"
          git push